### ISSUE TITLE
Failed Check still a success

### ISSUE THREAD

**Issue by WyntherKnight** [AngryBeaver/beavers-crafting#17]
Even if the skill roll failed, the crafting will still be a success, items still created.
![recipe](https://user-images.githubusercontent.com/66346903/212487059-72f5686b-2d1e-4940-8933-b24f5e9b7b7f.png)

**Comment by AngryBeaver** [comment]
ouch, but sadly i can not reproduce it.

I created a recipe with timetocraft and without and used also an ability instead of a skill but it works for me.

In the chat window it looks like it did no longer recognice the skill:
If the recipe had a skill it would print a number next to the check:
![image](https://user-images.githubusercontent.com/10677192/212497916-fbf08472-ec48-44ba-b512-e699ab933750.png)

Conclusion the crafting process is no longer the same as the recipe. -> if your recipe has a macro this macro can manipulate the crafting process. Maybe you have something in the advanced tab ?

Can you export the recipe you used so i may have a look at the raw data recipe. 
Also export the actor used all craftingprocesses should be stored there.

**Comment by AngryBeaver** [comment]
also possible that you may use an unknown module that do something with rolls ?

**Comment by WyntherKnight** [comment]
I tested it out on one of my test worlds (which I should have done). No other modules active. It's working as intended, so it might be another module interfering. 
![image](https://user-images.githubusercontent.com/66346903/212501274-816c8bdd-d4d0-4e03-96d2-2bba16194cc5.png)

Also, I noticed that under the crafting tab, If I craft again (clicking on the "play" button again) on a successful craft and got a failed roll, it deletes the resulted item. From the above image, i had 3 lines of "crafting queue" (first two was success, 3rd was a fail)
![image](https://user-images.githubusercontent.com/66346903/212501330-f3e1b562-acbd-4338-88ab-951c3a4eb162.png)
as you can see, the amulet count became "1"
![image](https://user-images.githubusercontent.com/66346903/212501339-05857803-c057-42a2-844c-c93d2553d54a.png)

**Comment by WyntherKnight** [comment]
I found the module, or rather two modules. Ready Set Roll for DnD5e combined with DF Manual rolls. Each one alone with the crafting module will function properly, but having these two active at the same time resulted in the error. I was able to generate the amulet in my inventory and It does not even show the status of the craft result.
![image](https://user-images.githubusercontent.com/66346903/212501929-f8567a2e-1747-490f-b6cd-a3732555157e.png)

**Comment by AngryBeaver** [comment]
thanks for testing this out i will have a look at ready set roll and df manual rolls.

Still the screenshots is showing me a bug i need to fix. They should ofc show up 100% finished if not you can click over and over on it until it fails... 
Not sure how that crafting process ended up that way can you right click your fighter actor and  export it so i can have a look at the crafting process data.

**Comment by AngryBeaver** [comment]
ah lol ok got the other bug when the worldTime is still zero it does not detect that the crafting is done. I will soon commit a fix for that.

**Comment by AngryBeaver** [comment]
Also got a workaround for the current version of ready set roll. but this feels as it might break at any moment i already asked the module developer to create a more reliable interface.

**Comment by AngryBeaver** [comment]
should work now. 2.2.2 
old data is broken you need to delete the craftings that should have been finished. 
I was not able to write a fix script that not also would have an unwanted side effect.
