### ISSUE TITLE
Ingredients not refunded on failure because they are deleted from the sheet.

### ISSUE THREAD

**Issue by SirGarhi** [AngryBeaver/beavers-crafting#42]
If a recipe locks all of the quantity of a particular ingredient, that ingredient gets removed from the character sheet entirely instead of having its quantity set to 0.

If the recipe then fails, and it's not set to consume the ingredients, the ingredient is not refunded and a document not found error is printed in the console.

If you still have that ingredient on the character sheet it correctly adds quantity back to it, though this is impacted by the bug in #41, if the item has a quantity of 0 the recipe will treat it as 1 before refunding the locked ingredients.

**Comment by AngryBeaver** [comment]
Short:
Yes you are right that might happen on broken components. 
I will think of a solution to it. One is your way but quantity 0 seems to be broken too. Another would be to insist on functional components or instead of removing it placing it somewhere else.

Long:
What is a "broken component": A component exists of name, type, ... and uuid. A broken components uuid is no longer be linked to anything found on foundry. (maybe you deleted the item you created the recipe with or deleted a module where the item had been in a compendium).
However at somepoint i decided to still allow such component in ingredients as i only needed name and type for an identity check on the actor itemList. And yes you found a problem with this aproach, for exactly this situation where i need to restore it from scratch.
For your solution I do not like the idea of having quantity 0 items in my inventory then it looks like i have it. I mostlikly can still use it weapons, armor, torch etc.

Workaround:
fix the broken component in the recipe open the recipe and remove the broken ingredient and add the same item again. Best would be items from a compendium.

**Comment by SirGarhi** [comment]
Hrm, so the core issue for my actual case is the interaction of anyOf ingredients with refunding ingredients, because my recipe uses an anyOf not a specific item from a compendium or anywhere else.

Unless I'm misunderstanding something, an anyOf will always result in a "broken component" if locking it results in a quantity 0 item and thus it gets deleted from the character sheet.

**Comment by AngryBeaver** [comment]
Ah yes ofc. thx for bringing it up, haven't thought about that.

**Comment by AngryBeaver** [comment]
should work now in 3.0.2 beavers-crafting and 2.0.0 beavers-system-interface and bsa-dnd5e 2.0.0
