### ISSUE TITLE
[Bug] As of Foundry v11 I found a couple of bugs.

### ISSUE THREAD

**Issue by ElPsyBone** [AngryBeaver/beavers-crafting#57]
It should show roll results and simple pop-up window in chat with materials used and progress done.
Now it only shows roll results and adds [[object Promimse](https://i.imgur.com/weeLZSp.png?1)] in chat instead of an actual window.

Recipe compendium doesn't close or minimize when you press "Start" (recipe is added in the crafting tab as intended).

Only GM can drag and drop materials to the recipe in slots of "anyOF", normal users can only press "Start" (and some of my players would like to spam same 5 mushrooms into the potion maker or any other combination there of) after that if the player had materials needed recipe will show up in crafting tab - ready to craft.
If not, recipe will take all the materials available from the player, add recipe into the crafting tab and automatically fail the craft deleting materials in the process (for example, character has 3 random mushrooms and 50 gold, player opens for example a random common potion recipe and presses "start", all 3 mushrooms and 5 gold needed for recipe would be deleted from the character and craft will be failed). As it doesn't add or preview materials in "anyOF" boxes (as players can't add them and module itself can't do that automatically)
Same of course happens if you add attendants to the recipe like crafting kits and specific classes etc.

With that in mind i would also like to add a feature request here to counter problem above. Can you make a promt or some window pop-up with "error text" or warning that says something like "you don't have enough materials to start the craft" or any safe brakes that will stop that from happening

And on the topic of random results. Can you make it so the crafting tab still shows just the table for the results (for example making a random potion, as soon as you add recipe into the crafting tab you can see the result of the craft if you open collapsed recipe) This one goes hand in hand with above one as if you can make it not consume materials for just adding or clicking the recipe it provides metagaming cucks a chance to just click "start" look at the "random" result and then cancel the craft

**Comment by AngryBeaver** [comment]
THX for your report.

I will have a look, i tested v11 a while ago when it was dev mode and the changelog did not seem to me to have an impact since then. But yes you are right its about time to test it again vs stable v11.

For the anyOf bug it might be this way already in v10. I have already a ticket for some improvements on anyOf but this will take some time. Next stop i am planning to popup a dialog for all not declared decissions in the recipe when starting one. Won't be perfect but will help with your probelem a bit.

Save fail maybe i can do some improvements, but nothing clean. it correlates to recipe macros.

Show random result is possible but i would need to rework usage of recipe macros to make it clean. (This is not simple).

Warning i am currently super lazy with this project so do not expect me working instantly on it. 
However I will priotise  v11 stable as highest pio for this project. Then I will continue working on conditional ingredients (another request) that may result in improving your mention anyOf bug.
The rest of this will come some time later.

**Comment by ElPsyBone** [comment]
Appreciated! Will wait and report any more findings.

**Comment by AngryBeaver** [comment]
3.1.6 released fixing the two major bugs in v11.

**Comment by ElPsyBone** [comment]
Went into the game. Can confirm recipe compendium now properly closes when you press start, and [Object promise] is gone now it shows chat window with craft results. Thank you.

**Comment by AngryBeaver** [comment]
v3.1.7 released fixing the anyOf now allowing also player to drag and drop items on it. (that was stupid, it always was only possible for dms)

the rest in this ticket is pushed further down the pipeline. I am still working on "or conditions" and this is internally massivly breaking so that will take me some time.

**Comment by ElPsyBone** [comment]
Thank you for the work and that you did it in such short time notice. We starting a campaign next Saturday and crafting is a big thing there, you are a lifesaver!
