### ISSUE TITLE
Feature Request - Crafted by

### ISSUE THREAD

**Issue by tirzah2** [AngryBeaver/beavers-crafting#61]
Hi, is there a way to add the possibility to add, maybe in the description of a crafted item, the line: Crafted by "name of the crafter"
this could be very useful in case i want to implement an enchanting system, and allow players to enchat items only if they have been crafted by players, therefore making the crafting even more important.

**Comment by AngryBeaver** [comment]
Well first of there are limitations: crafting will merge identity same objects. Identity same is defined in most cases as item.name + item.type. So it would be possible that you have e.g. already a sword in your inventory then craft another sword and you would end up with one sword item in your inventory with quantity two ! this "sword item" is then marked as crafted althou only one of them is crafted.

Another thing is that this module is no longer only for crafting you can also use it for quests or for your enchanting or for any progressing you can think of. So generelly marking the result of a recipe as "crafted" would be incorrect. 

That said it should be possible it seems simple enough that i could priotise it up. But i am currently in the middle of a feature that just keeps breaking my inner logic and i want to finish that first. So can't give you an estimation but it would be the upmost feature after my next 3.2.0 release.

Do you need it human readable or machine readable or both ?
I would prefer the second so i could store it in the item data an extended fields that are not visible in the editor but readable from e.g. a macro like an enchantment recipe that uses an "anyOf" item designed to find explicitly crafted items.

Do you need to store the person that has crafted it ? maybe the item get transfered from one actor to another is it important who crafted it. I would not recommend it as it seems to have not much use but again when you need it i would prefer machine readability.

human readable i would prefer the syntax "produced by Recipe" instead of crafted if you need human readable.
Machine readable i would add some additional metadata like the folder field you recipe has defined. -> This would be the place to seperate diffrent types of Recipes like e.g. Quest, Crafting, Gathering etc... which would allow you to further specialize what items are usable in your postprocess. e.g. only items that had been in the folder starting with "Crafting"

**Comment by tirzah2** [comment]
Maybe just flagged as crafted?
And then when they try to do a recipe that creates a longsword +1, if the sword is not crafted (anyof longsword tagged crafted) then it won't work..

**Comment by AngryBeaver** [comment]
A flagg is attached to all updated and created items.
"created" items are save to use in this way "updated" has possible created a stack with multiple items and the complet stack is now [flagged](https://github.com/AngryBeaver/beavers-crafting/blob/main/README.md#result).
v3.2.2
