### ISSUE TITLE
[BUG][Module Compatibility 'item-linking'] If the final recipe object is in a compendium, the `flags.beavers-crafting.status` flag is not applied to that object

### ISSUE THREAD

**Issue by p4535992** [AngryBeaver/beavers-crafting#76]
**Details:**

_Core Version:_ 11.307
_System:_ dnd5e 2.3.0 (Atropos) 
_Modules:_ 
–	beavers-crafting 3.2.2 (angryBeaver)
–	beavers-system-interface 2.1.4 (angryBeaver)
–	bsa-dnd5e 2.0.1 (angryBeaver)
–	forien-copy-environment v2.2.0 (Blair McMillan, Forien)
–	item-linking 1.0.14 (Elizeu Angelo)

**NOTE: If the final recipe object is not in a compendium the workflow is working !!!**

Then the case is special, I am using two modules "Item Linking" and "Beaver Crafting".

The recipe goes to retrieve the final object (in this case a potion) from a compendium.

For some reason at the end of the process on the final item the `flags.beavers-crafting.status` flag is missing.

With a little debugging, I verified that it is because the `itemChanges` object at this row https://github.com/AngryBeaver/beavers-crafting/blob/2c43ca1880e2405d9db960be3d14e4f3f06e7044/src/Crafting.ts#L373 has the arrays all empty.

The  `itemChanges`  value is:
```
{
    create: []
    update: [],
    merge: [],
    delete: []
}
```
This should not happen right ? at least one element must be present in one of the arrays (I think).

Let me know it if you need other informations.

**Some videos:** 
https://i.imgur.com/GzaAZxm.gif
![img](https://i.imgur.com/GzaAZxm.gif)

**Comment by AngryBeaver** [comment]
Well i have to look more closely to this but first things:


1) this flag is only a minor feature:
Beavers Crafting does not really need that flag in order to work it is for the rare cases when you want to know which items had been crafted e.g. build a recipe that only accept crafted items.
2) bug only in combination with item-linking module:
I haven't used item-linking before but from the description of the author it seems that it might be possible that i can not edit that linked item to add a flag: "Players can edit linked items only partially, most fields are disabled."

**Comment by AngryBeaver** [comment]
yes that is it usually this method returns something:
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/b576bb5e-f792-47ea-a4ab-3d1b4f81a914)
and this happens if i enable the item-linking module:
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/1ee6e420-0286-4dfe-b1eb-071375ed7509)

i might be able to workaround that but maybe item-linking can fix it.

**Comment by p4535992** [comment]
kk i open a issue on the item-linking project, ty for the fast investigation.

**Comment by p4535992** [comment]
Related to https://github.com/elizeuangelo/fvtt-module-item-linking/issues/3

**Comment by p4535992** [comment]
Solved from magus side
