### ISSUE TITLE
[Feature Request] Time to Craft

### ISSUE THREAD

**Issue by mnoreke** [AngryBeaver/beavers-crafting#9]
The time to craft (minutes/hours/days/weeks) should be able to be input on a recipe.

**Comment by AngryBeaver** [comment]
1.) The easy way: Add a description for recipes where you can also add this as text only. Not so easy to display that as the space is already thin. Probably start using tabs in RecipeCreation and then also in the RecipeCompendium. What is the initial prefered tab ? Well probably the user is more interested in what he gets and what he needs so this tab is initial closed. -> users will mostlikly seldom click on the tab therefor not seeing what ever is written here. -> not usefull.

2.) Another special field defineing time. less space to display but then users expect something to happen with that so combining it to some time module. -> increase complexity. 
2a) Delaying craft by the time: does the user consume the items see the chat message get the result after the time or even parts before parts after -> increase complexity again.
2b) Easyway disable crafting as long as it takes for the previously crafted. 

If i start with this it will be either 1 if i find a way for the ui or 2b but it has low prio due to its complexity.

**Comment by CalabC** [comment]
I'm no coder, but I thought that maybe this could help.

Plan A: You could use the module "Simple Calender" to help keep track of things. (For others)

Plan B: On the whole coding side of things, 
-Modules for stats "Midi QOL", "Dynamic effects using Active Effects" and "Times Up" could help affect this crafting module in some ways, but again, I'm not a coding soooo. And, you could also somehow integrate Simple Calender to auto-keep track of things.

**Comment by AngryBeaver** [comment]
Well I kinda did what has been requested you can now start a crafting process and end it at a later time. v2.2.0 

 I decided against a coupling to worldTime as the time spend for the crafting process can not be expressed in amount of time consumed in the world as crafting is a downtime activity and mostlikely not the main activity your char is doing. When your recipe does consume lets say 8 hours work then it should not be finished overnight after you take a sleep.

Other similarities that are also not bound to worldtime. The rest actions in dnd5e is not coupled to any worldtime consumption.
