### ISSUE TITLE
Recipes Error

### ISSUE THREAD

**Issue by SecretSquirrel77** [AngryBeaver/beavers-crafting#94]
Hello and love your work!
On DnD5e with Beaver's crafting and all related dependencies, I noticed my players list of recipes was much smaller one day than it was before. I opened by recipes folder in my items tab and the recipes that I had pulled from the Beavers Crafting Compendium all look like the picture.

The recipes in the compendium are the same way. This seems to have happened around the time I migrated to DnD5e 2.4.x

I'm unsure why my existing imported recipes and compendium recipes seem to be failing but any recipes I created myself still work as expected. I have the latest 5e (2.4.1) and the latest Beavers Crafting mods (Interface 2.1.6 and Crafting 3.3.0)
![image](https://github.com/AngryBeaver/beavers-crafting/assets/77705375/614449fe-bef4-41f6-ba28-afc299039c59)

**Comment by AngryBeaver** [comment]
yeah the dnd2.4 did break some stuff for my modules. Also beavers-potion module is rather hard to maintain due to its internal dependencies those potion recipes are based on a very old beavers-crafting version. 

All recipes not within a compendium should be automatically be migrated whenever a breaking new version of beavers-crafting had been released. But compendiums can not be automatically be migrated.  

I would need to recreate those potion recipes not sure when i get to this.

**Comment by AngryBeaver** [comment]
v2.0.1
